### PR TITLE
BIT-7 Cleaning code base

### PR DESCRIPTION
**Pull request by Tawishi**
Reformatted code

### CODE REVIEW

**Comment by rexdivakar** [comment]
I have updated the PR tag so it gets recognized by the latest JIRA ticket @Tawishi

**Review by rexdivakar — CHANGES_REQUESTED** [review]
Hey @Tawishi can u please remove this file api/static/btrs1086f7057eab27869378e5ebcd230b7dbiuy89.png and clear the debug.log file (keep it with some sample text )

**Comment by Tawishi** [comment]
> Hey @Tawishi can u please remove this file api/static/btrs1086f7057eab27869378e5ebcd230b7dbiuy89.png and clear the debug.log file (keep it with some sample text )

What do you mean by _sample text_?

**Comment by rexdivakar** [comment]
yes, remove the existing ones and replace a sample word and push it

**Review by rexdivakar — APPROVED** [review]

**Pull request merged**
